plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.9'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.homs'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '17'
targetCompatibility = '17'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

ext {
	lombokVersion = '1.18.30'
	springDocVersion = '2.5.0'
	jacksonVersion = '2.13.0'
}

dependencies {
	// Core Spring Boot dependencies
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-hateoas'
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.15'

	// Database
	implementation 'org.mariadb.jdbc:mariadb-java-client:1.5.7'
	runtimeOnly 'com.h2database:h2'

	// Utils
	compileOnly "org.projectlombok:lombok:${lombokVersion}"
	annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
	compileOnly 'org.projectlombok:lombok:1.18.30' // Lombok scope 'provided' equivalent

	// dotenv
	implementation 'me.paulschwarz:spring-dotenv:4.0.0'

	// Testing dependencies
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testCompileOnly 'org.projectlombok:lombok:1.18.26'
	testAnnotationProcessor 'org.projectlombok:lombok:1.18.26'
}

 tasks.named("test"){
	 useJUnitPlatform()
 }