version: '3.8'
services:
  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: account-manager
    ports:
      - "3306:3306"
    networks:
      - app-network
  app:
    build: .
    environment:
      - DB_URL=jdbc:mariadb://db:3306/account-manager
      - DB_USER=root
      - DB_PASS=admin
      - SPRING_PROFILES_ACTIVE=test
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network: