spring:
  application:
    name: account-rest-api
  datasource:
    url: ${DB.URL}
    username: ${DB.USER}
    password: ${DB.PASS}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 1
