spring:
    application:
        name: account-rest-api
    datasource:
        url: ${DB.URL}
        username: ${DB.USER}
        password: ${DB.PASS}
        hikari:
            maximum-pool-size: 1 
