spring:
  application:
    name: account-rest-api
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    dialect: org.hibernate.dialect.PostgreSQLDialect