CREATE TABLE IF NOT EXISTS cli_account (
    account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    balance NUMERIC(10,2) NOT NULL DEFAULT 0.00 CHECK (balance >= 0),
    alias VARCHAR(60) NOT NULL,
    type VARCHAR(20) NOT NULL,
    creation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cli_category(
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(255) NOT NULL,
    creation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cli_transaction(
    transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMERIC(12,2) NOT NULL DEFAULT 0.00 CHECK (amount > 0),
    type VARCHAR(10) NOT NULL CHECK (type IN ('EXPENSE', 'INCOME')),
    date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    alias VARCHAR(60),
    transaction_account INT NOT NULL,
    transaction_category INT NOT NULL,
    CONSTRAINT fk_transaction_account
        FOREIGN KEY (transaction_account)
        REFERENCES cli_account(account_id)
        ON UPDATE CASCADE,
    CONSTRAINT fk_transaction_category
        FOREIGN KEY (transaction_category)
        REFERENCES cli_category(category_id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);